version: "3.8"
services:
  backend:
    image: yourdockerhubuser/myapp-backend:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"

  frontend:
    image: yourdockerhubuser/myapp-frontend:latest
    restart: always
    ports:
      - "80:80"


