server {
    listen 80;

    location / {
        proxy_pass http://react_frontend:3000;
    }

    location /api/ {
        proxy_pass http://node_backend:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
